// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOq9vxAk830PULAUMNx6JOnCFjEqhuhI',
    appId: '1:635920060047:web:e24785fffd5eff63562afa',
    messagingSenderId: '635920060047',
    projectId: 'anesthesia-icu-app',
    authDomain: 'anesthesia-icu-app.firebaseapp.com',
    storageBucket: 'anesthesia-icu-app.firebasestorage.app',
    measurementId: 'G-HM8TKPXW3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1jnw2Ml8hlTELxrvkIkX18-cuYNj7384',
    appId: '1:635920060047:android:9256d371ed349d49562afa',
    messagingSenderId: '635920060047',
    projectId: 'anesthesia-icu-app',
    storageBucket: 'anesthesia-icu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQD4o_Z3LN_v3sRP-Jj7qFB_GyXpS82wc',
    appId: '1:635920060047:ios:676fad4d4546eb72562afa',
    messagingSenderId: '635920060047',
    projectId: 'anesthesia-icu-app',
    storageBucket: 'anesthesia-icu-app.firebasestorage.app',
    iosBundleId: 'com.medical.anesthesiaIcuCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQD4o_Z3LN_v3sRP-Jj7qFB_GyXpS82wc',
    appId: '1:635920060047:ios:676fad4d4546eb72562afa',
    messagingSenderId: '635920060047',
    projectId: 'anesthesia-icu-app',
    storageBucket: 'anesthesia-icu-app.firebasestorage.app',
    iosBundleId: 'com.medical.anesthesiaIcuCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWOq9vxAk830PULAUMNx6JOnCFjEqhuhI',
    appId: '1:635920060047:web:33c6084cdcf3273b562afa',
    messagingSenderId: '635920060047',
    projectId: 'anesthesia-icu-app',
    authDomain: 'anesthesia-icu-app.firebaseapp.com',
    storageBucket: 'anesthesia-icu-app.firebasestorage.app',
    measurementId: 'G-ZQNWQB6ES8',
  );
}
